const mongoose = require("mongoose");

const categorySchema = new mongoose.Schema(
    {
        name: { 
            type: String, 
            required: true, 
            unique: true, 
            trim: true 
        },
        slug: { 
            type: String, 
            unique: true, 
            lowercase: true 
            // Not required - will be auto-generated by pre-validate hook
        },
        description: { type: String, default: "" },
        color: { type: String, default: "#6366f1" } // Default indigo color
    }, 
    { timestamps: true }
);

// Create slug from name before validation (so validation doesn't fail)
categorySchema.pre("validate", function(next) {
    if (this.isModified("name") || !this.slug) {
        this.slug = this.name
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-+|-+$/g, "");
    }
    next();
});

const Category = mongoose.model("Category", categorySchema);

module.exports = Category;